<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <UserSecretsId>dotnet-TravelMemory.Worker-d33a92af-040d-4d93-811c-f01b9ea8c718</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Azure.Storage.Blobs" />
    <PackageReference Include="Aspire.Azure.Storage.Queues" />
    <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer" />
    <PackageReference Include="Magick.NET-Q8-AnyCPU" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TravelMemory.Domain\TravelMemory.Domain.csproj" />
    <ProjectReference Include="..\TravelMemory.Persistence\TravelMemory.Persistence.csproj" />
    <ProjectReference Include="..\TravelMemory.ServiceDefaults\TravelMemory.ServiceDefaults.csproj" />
  </ItemGroup>
</Project>
